### PR TITLE
Ensure bindMethods can bind methods all the way up a proto chain.

### PR DESCRIPTION
**Pull request by gnarf**
- Allow passing a parent constructor (default to Object) and walk
  up the thisValue's prototype chain until we get to the parent.

### CODE REVIEW

**Comment by gnarf** [comment]
cc @z @cowboy -- Just FYI, I redid this `bindMethods` fix on this repo

**Comment by cowboy** [comment]
Are there tests? Should this be its own module?

**Comment by gnarf** [comment]
There isn't a `test` folder here, but if you wanted me to put this into another repo you have, which has tests, I'll happily write some.

**Comment by bobholt** [comment]
Oh yeah, tests. Thanks, @gnarf!

**Pull request merged**
